### ISSUE TITLE
Make this plugin open-source

### ISSUE THREAD

**Issue by travishathaway** [anaconda/conda-anaconda-telemetry#51]
### What should be done?

- [x] Make sure any sensitive information has been removed (including this issue 😉)
- [x] Publish the documentation website that has been created for this project
- [x] Create issue templates for "bugs" and "feature requests" (#81)
- [ ] ~Add a code of conduct (see: [Adding a code of conduct to your project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project))~
  - @jezdez pointed out something very important: we do not have a way to enforce code of conduct violations, so it does not make sense to include it for our project unfortunately. Additionally, it is not clear which one should be added as Anaconda does not have a community code of conduct for its projects. I will therefore not be adding one to our project.
- [x] Add contribution guidelines to the README (#80)
- [x] Add a project FAQ in the documentation (#82)
- [x] Add a license
